services:
    glavweb_content_block.twig.content_block_extension:
        class:     Glavweb\ContentBlockBundle\Twig\ContentBlockExtension
        arguments: ["@request_stack", "@doctrine", "@security.authorization_checker"]
        pablic:    false
        tags:
            - { name: twig.extension }

